# Generated by Django 2.1.7 on 2019-02-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
