# Generated by Django 2.1.7 on 2019-05-03 21:52

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('graphic', models.ImageField(upload_to=main.models.ImageContent.directory)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImageElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphic', models.ImageField(upload_to=main.models.ImageElement.directory)),
                ('subtitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageListing',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='imageelement',
            name='my_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ImageListing'),
        ),
    ]
