# Generated by Django 2.2.2 on 2019-06-24 22:29

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', max_length=100, verbose_name='Nazwa')),
                ('icon', models.CharField(default='question', max_length=100, verbose_name='Ikona')),
                ('url', models.CharField(max_length=100, verbose_name='Adres')),
                ('is_internal', models.BooleanField(verbose_name='Wewnętrzny')),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ImageElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphic', models.ImageField(upload_to=main.models.ImageElement.directory)),
                ('subtitle', models.CharField(max_length=100)),
                ('my_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ImageListing')),
            ],
        ),
    ]
