# Generated by Django 2.1.7 on 2019-06-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('is_internal', models.BooleanField()),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
    ]
