# Generated by Django 2.1.7 on 2019-06-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default='Unnamed', max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='icon',
            field=models.CharField(default='question', max_length=100),
        ),
    ]
