# Generated by Django 2.1.7 on 2019-02-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190222_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gelement',
            name='graphic',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
