# Generated by Django 2.1.7 on 2019-02-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190225_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gelement',
            name='graphic',
            field=models.ImageField(upload_to=''),
        ),
    ]
