# Generated by Django 2.1.7 on 2019-03-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190228_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gelement',
            name='graphic',
            field=models.ImageField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x7f845df18438>/'),
        ),
    ]
