# Generated by Django 2.1.7 on 2019-03-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190302_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gelement',
            name='graphic',
            field=models.ImageField(upload_to="<class 'main.models.Glist'>/"),
        ),
    ]
