# Generated by Django 2.1.7 on 2019-06-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190608_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='icon',
            field=models.CharField(default='question', max_length=100, verbose_name='Ikona'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_internal',
            field=models.BooleanField(verbose_name='Wewnętrzny'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(default='Unnamed', max_length=100, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=100, verbose_name='Adres'),
        ),
    ]
