# Generated by Django 2.1.7 on 2019-06-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190608_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='codename',
            field=models.CharField(default='--', max_length=100, verbose_name='Sprzężenie'),
        ),
    ]
