# Generated by Django 2.1.7 on 2019-03-02 18:09

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190302_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphic', models.ImageField(upload_to=main.models.GraphicalItem.directory)),
                ('subtitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='gelement',
            name='manager',
        ),
        migrations.RenameModel(
            old_name='Glist',
            new_name='GraphicalItemManager',
        ),
        migrations.DeleteModel(
            name='Gelement',
        ),
        migrations.AddField(
            model_name='graphicalitem',
            name='my_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.GraphicalItemManager'),
        ),
    ]
