# Generated by Django 2.2.2 on 2019-06-22 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_page_codename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='codename',
        ),
    ]
